# Generated by Django 4.0.1 on 2022-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=10, null=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.IntegerField(max_length=12)),
                ('nick_name', models.SlugField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('student', 1), ('teacher', 2), ('principal', 3)], default=1, max_length=15)),
                ('gender', models.CharField(choices=[('male', 'm'), ('female', 'f')], default='m', max_length=30)),
                ('status', models.CharField(choices=[('pending', 1), ('active', 2), ('inactive', 3), ('deleted', 4)], default=1, max_length=15)),
            ],
            options={
                'db_table': 'user_info',
                'ordering': ['first_name'],
            },
        ),
    ]
