# Generated by Django 4.0.1 on 2022-01-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending')], default='pending', max_length=15)),
            ],
            options={
                'db_table': 'technology_info',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generics_views.technologyinfo')),
            ],
            options={
                'db_table': 'framework_info',
            },
        ),
    ]
