# Generated by Django 4.0.1 on 2022-01-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generics_views', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frameworkinfo',
            old_name='technology_id',
            new_name='technology',
        ),
    ]
